### ISSUE TITLE
[Bug] Adding a dial from context menu resets customizations

### ISSUE THREAD

**Issue by mg979** [Mimiste/YayAnotherSpeedDial#11]
Reproduce:

* open speed dial
* customize dials
* add a new dial from a tab
* go back to the speed dial

All customizations are gone, including new tabs. Basically you have to restart Firefox after customizing anything to be safe, it's very annoying.

**Comment by loic-martinez-freelance** [comment]
Hello

I reproduced the problem, it will be fixed in the next update

**Comment by mg979** [comment]
Thanks
