### ISSUE TITLE
Update to the spanish translation

### ISSUE THREAD

**Issue by rayman89** [Mimiste/YayAnotherSpeedDial#6]
Here is the update for the Spanish translation. 

```
 "account_created":{
    "message":"<b>¡Tu cuenta ha sido creada!</b> <br><br> Con ella tus marcadores podrán ser sincronizados con cualquier dispositivo. <br><br> El uso de la cuenta es totalmente gratuito y me aseguraré de que así sea siempre.<br> Si deseas ayudarme a cubrir los costos del servidor, puedes hacerlo enviando una donación.<br><br> ¡Gracias!",
    "description": ""
  },
  "ok_help":{
    "message":"¡Si, deseo ayudar!",
    "description": ""
  },
  "no_help":{
    "message":"No, gracias. Quizás después.",
    "description": ""
  },
  "sort_by_name":{
    "message":"Ordenar por nombre",
    "description": ""
  },
  "sort_by_rating":{
    "message":"Ordenar por puntuación",
    "description": ""
  },
  "sort_by_download":{
    "message":"Ordenar por descargas",
    "description": ""
  },
  "theme_score_set":{
    "message":"Tu puntuación ha sido enviada",
    "description": ""
  },
  "theme_score_updated":{
    "message":"Tu puntuación ha sido actualizada",
    "description": ""
  },
  "like_theme":{
    "message":"¿Te gusta este tema?",
    "description": ""
  },
  "share_theme_page":{
    "message":"Comparte tu tema",
    "description": ""
  },
  "share_theme_form":{
    "message":"Completa este formulario para compartir tu tema con los demás.<br> Sólo el tema será compartido. Ninguno de tus marcadores será enviado.<br> ¡Asegurate de haber salvado las modificaciones a tu tema antes de enviarlo!",
    "description": ""
  },
  "share_theme_title":{
    "message":"Nombre de tu tema",
    "description": ""
  },
  "share_theme_name":{
    "message":"Tu nombre o apodo",
    "description": ""
  },
  "share_theme_mail":{
    "message":"Tu mail (Sólo para contacto. Tu mail no sera mostrado públicamente.)",
    "description": ""
  },
  "share_theme_screenshot":{
    "message":"Una captura de pantalla de tu tema",
    "description": ""
  },
  "share_theme_ok":{
    "message":"¡Tu tema ha sido enviado. Será evaluado y publicado a la brevedad! ¡Muchas gracias!",
    "description": ""
  },
  "share_theme_error_fields":{
    "message":"Por favor llena todos los campos requeridos",
    "description": ""
  },
  "share_theme_error_screenshot":{
    "message":"Por favor envía una captura de pantalla de tu tema",
    "description": ""
  },
  "importFromFVD_note": {
    "message": "Por favor pega aquí el resultado de la exportación de Speed Dial [FVD]",
    "description": ""
}
```

**Comment by rayman89** [comment]
BTW when is the fix for the missing favicons coming?

**Comment by loic-martinez-freelance** [comment]
Thank you for the update! 👍 
Can you please remember me the missing favicons problem?

**Comment by rayman89** [comment]
Here is the last part of our conversation if you wish I can send you the full conversation if you have deleted the mails I sent you or something.

>Le lun. 2 juil. 2018 à 18:26, Lara a écrit :

>  It's still buggy but I noticed that if I go to "modify bookmark" and select but don't press save first "from a file" then "from a link" and finally back to automatic the letter appears and then I can save and it stays but I cannot do that on tab settings so it has to be done one by one. I also tested deleting the tab and creating it again but it did not fix the issue.



>    7/2/2018 at 4:16 PM 

>Alright now I see the problem!
>It will be corrected as soon as possible
>Thanks!
>Loïc

**Comment by loic-martinez-freelance** [comment]
okay! Didn't recognized your nickname.
Well, I done some work for this problem, it's still not working? It was one of the bug fixes between the version 1.0.8.11 and 1.0.8.16

**Comment by rayman89** [comment]
ver .16 and .90 were the versions you posted after you sent me that last message and none of those versions did solve the issue.

**Comment by rayman89** [comment]
Are you still working on the fix?

**Comment by loic-martinez-freelance** [comment]
Please can you show me if possible, the problem with some screenshots or a video?

**Comment by rayman89** [comment]
![image](https://user-images.githubusercontent.com/5449042/44468643-4d71c780-a5eb-11e8-8467-4f0b7a145251.png)


that is how it looks no letters at all. I tried resetting the config and creating tabs from scratch but it's always the same: no letter favicon.

I found a way to make 1 appear but I cannot do this in bulk (also this should be done automatically by default when you favicon is found not manually AFIK)  if I go to "modify bookmark" and select without pressing save in between:  1) "from a file"  2)"from a link" and finally back to 3) "automatic"; the letter appears in the preview and then I can save and it stays but like I said I cannot do that on tab settings so it has to be done one by one. 

I also tested this on a clean profile with default options for the addon and still no letter favicon

![image](https://user-images.githubusercontent.com/5449042/44468286-7b0a4100-a5ea-11e8-9143-d7966eac3ca2.png)

Steps to replicate:

1) add this page as a bookmark : http://www.codecguide.com/  (this is only 1 example it happens with all the sites without favicon)

2) Go to addon's settings > backup

3) on "Create a tab from one of my browser bookmarks folders" select the folder containing the created bookmark.

4) You'll see that the bookmark favicon is blank instead of containing the "C" letter favicon

**Comment by rayman89** [comment]
@Mimiste was this info useful?

**Comment by loic-martinez-freelance** [comment]
Can you tell me if it's ok in the new version?

**Comment by rayman89** [comment]
It's mostly working but some sites that have favicons and somehow cannot be retrieved remain without any favion. 
![image](https://user-images.githubusercontent.com/5449042/44994414-2c529480-af64-11e8-970e-fd1e59f6c687.png)

Url: https://www.thinkbroadband.com/download

Another example http://tumblr.tastefullyoffensive.com/

**Comment by rayman89** [comment]
Were you able to confirm this? @Mimiste

**Comment by loic-martinez-freelance** [comment]
Yes, I saw where this came from.
But actually, I'm completely rewriting the extension using Typescript and Angular 6. It will fix a lot of things, improve overall performances and make it way easier for me to add new functionalities.
